2019/01/21 13:17:31 [error] 3872#3872: *246 open() "/srv/django_mysite/favicon.ico" failed (2: No such file or directory), client: 101.94.255.223, server: , request: "GET /favicon.ico HTTP/1.1", host: "106.14.146.79", referrer: "http://106.14.146.79/"
2019/01/21 13:19:55 [error] 3872#3872: *264 connect() failed (111: Connection refused) while connecting to upstream, client: 101.94.255.223, server: , request: "GET / HTTP/1.1", upstream: "uwsgi://127.0.0.1:8086", host: "106.14.146.79", referrer: "http://106.14.146.79/write.blog/"
2019/01/21 13:22:38 [error] 3872#3872: *266 open() "/srv/django_mysite/static/img/logo/favicon.ico" failed (2: No such file or directory), client: 101.94.255.223, server: , request: "GET /static/img/logo/favicon.ico HTTP/1.1", host: "106.14.146.79", referrer: "http://106.14.146.79/"
2019/01/21 13:25:04 [error] 3872#3872: *275 connect() failed (111: Connection refused) while connecting to upstream, client: 101.94.255.223, server: , request: "GET / HTTP/1.1", upstream: "uwsgi://127.0.0.1:8086", host: "106.14.146.79", referrer: "http://106.14.146.79/write.blog/"
2019/01/21 13:25:06 [error] 3872#3872: *275 connect() failed (111: Connection refused) while connecting to upstream, client: 101.94.255.223, server: , request: "GET / HTTP/1.1", upstream: "uwsgi://127.0.0.1:8086", host: "106.14.146.79", referrer: "http://106.14.146.79/write.blog/"
2019/01/21 13:25:48 [error] 3872#3872: *278 connect() failed (111: Connection refused) while connecting to upstream, client: 169.239.215.33, server: , request: "GET / HTTP/1.1", upstream: "uwsgi://127.0.0.1:8086", host: "106.14.146.79:80"
2019/01/21 13:26:18 [error] 3872#3872: *282 connect() failed (111: Connection refused) while connecting to upstream, client: 101.94.255.223, server: , request: "GET / HTTP/1.1", upstream: "uwsgi://127.0.0.1:8086", host: "106.14.146.79", referrer: "http://106.14.146.79/write.blog/"
2019/01/21 13:26:19 [error] 3872#3872: *282 connect() failed (111: Connection refused) while connecting to upstream, client: 101.94.255.223, server: , request: "GET / HTTP/1.1", upstream: "uwsgi://127.0.0.1:8086", host: "106.14.146.79", referrer: "http://106.14.146.79/write.blog/"
2019/01/21 13:27:43 [error] 3872#3872: *287 connect() failed (111: Connection refused) while connecting to upstream, client: 101.94.255.223, server: , request: "GET / HTTP/1.1", upstream: "uwsgi://127.0.0.1:8086", host: "106.14.146.79"
2019/01/21 13:27:47 [error] 3872#3872: *287 connect() failed (111: Connection refused) while connecting to upstream, client: 101.94.255.223, server: , request: "GET / HTTP/1.1", upstream: "uwsgi://127.0.0.1:8086", host: "106.14.146.79"
2019/01/21 13:28:25 [error] 3872#3872: *287 connect() failed (111: Connection refused) while connecting to upstream, client: 101.94.255.223, server: , request: "GET / HTTP/1.1", upstream: "uwsgi://127.0.0.1:8086", host: "106.14.146.79"
2019/01/21 13:31:05 [error] 3872#3872: *291 connect() failed (111: Connection refused) while connecting to upstream, client: 101.94.255.223, server: , request: "GET / HTTP/1.1", upstream: "uwsgi://127.0.0.1:8086", host: "106.14.146.79"
2019/01/21 13:31:28 [error] 3872#3872: *291 connect() failed (111: Connection refused) while connecting to upstream, client: 101.94.255.223, server: , request: "GET / HTTP/1.1", upstream: "uwsgi://127.0.0.1:8086", host: "106.14.146.79"
2019/01/21 13:31:30 [error] 3872#3872: *291 connect() failed (111: Connection refused) while connecting to upstream, client: 101.94.255.223, server: , request: "GET / HTTP/1.1", upstream: "uwsgi://127.0.0.1:8086", host: "106.14.146.79"
2019/01/21 13:33:22 [error] 3872#3872: *302 open() "/srv/django_mysite/static/img/favicon.ic" failed (2: No such file or directory), client: 101.94.255.223, server: , request: "GET /static/img/favicon.ic HTTP/1.1", host: "106.14.146.79", referrer: "http://106.14.146.79/"
2019/01/21 13:36:26 [error] 3872#3872: *304 connect() failed (111: Connection refused) while connecting to upstream, client: 101.94.255.223, server: , request: "GET /test HTTP/1.1", upstream: "uwsgi://127.0.0.1:8086", host: "106.14.146.79"
2019/01/21 13:36:28 [error] 3872#3872: *304 connect() failed (111: Connection refused) while connecting to upstream, client: 101.94.255.223, server: , request: "GET /test HTTP/1.1", upstream: "uwsgi://127.0.0.1:8086", host: "106.14.146.79"
2019/01/21 13:36:31 [error] 3872#3872: *304 connect() failed (111: Connection refused) while connecting to upstream, client: 101.94.255.223, server: , request: "GET / HTTP/1.1", upstream: "uwsgi://127.0.0.1:8086", host: "106.14.146.79", referrer: "http://106.14.146.79/write.blog/"
2019/01/21 13:36:34 [error] 3872#3872: *304 connect() failed (111: Connection refused) while connecting to upstream, client: 101.94.255.223, server: , request: "GET / HTTP/1.1", upstream: "uwsgi://127.0.0.1:8086", host: "106.14.146.79", referrer: "http://106.14.146.79/write.blog/"
2019/01/21 13:36:38 [error] 3872#3872: *309 connect() failed (111: Connection refused) while connecting to upstream, client: 101.94.255.223, server: , request: "GET / HTTP/1.1", upstream: "uwsgi://127.0.0.1:8086", host: "106.14.146.79"
2019/01/21 13:39:58 [error] 3872#3872: *311 connect() failed (111: Connection refused) while connecting to upstream, client: 101.94.255.223, server: , request: "GET / HTTP/1.1", upstream: "uwsgi://127.0.0.1:8086", host: "106.14.146.79"
2019/01/21 14:19:07 [error] 997#997: *13 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 101.94.255.223, server: , request: "GET / HTTP/1.1", upstream: "uwsgi://127.0.0.1:8086", host: "106.14.146.79"
2019/01/21 14:34:18 [error] 997#997: *39 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 101.94.255.223, server: , request: "GET / HTTP/1.1", upstream: "uwsgi://127.0.0.1:8086", host: "106.14.146.79"
